FROM appz/dashboard:2.0

#COPY images/logo.png /var/www/server/.local/static/logo.png
#COPY images/logo.png /var/www/client/dist/assets/images/logocc.png
#COPY images/logo_login.png /var/www/client/dist/assets/images/cloudcontrol.png

ENV ADMIN_PANEL_TITLE='AppZ Dashboard'
ENV ADMIN_PANEL_COLOR='#01a8ef'
